# Generated by Django 3.1.6 on 2021-04-11 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_options', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=50)),
                ('description', models.CharField(default='', max_length=100)),
                ('duration', models.IntegerField()),
                ('level', models.IntegerField()),
                ('information', models.CharField(default='', max_length=100)),
                ('mission', models.CharField(default='', max_length=100)),
                ('caution', models.CharField(default='', max_length=100)),
                ('controller_type', models.CharField(default='simple', max_length=100)),
                ('controller_variables', models.CharField(max_length=1000)),
                ('ai_name', models.CharField(default='AI', max_length=20)),
                ('human_name', models.CharField(default='Human', max_length=20)),
                ('summarize_token', models.IntegerField()),
                ('info', models.CharField(default='', max_length=100)),
                ('options', models.CharField(default='{}', max_length=200)),
                ('response_length', models.IntegerField(default=150)),
                ('temperature', models.DecimalField(decimal_places=3, default=0.9, max_digits=4)),
                ('top_p', models.DecimalField(decimal_places=3, default=1, max_digits=4)),
                ('frequency_penalty', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('presence_penalty', models.DecimalField(decimal_places=3, default=0.6, max_digits=4)),
                ('voice', models.CharField(default='en-US_AllisonV2Voice', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=200)),
                ('visible', models.BooleanField(default=True)),
                ('editable', models.BooleanField(default=True)),
                ('send', models.BooleanField(default=True)),
                ('include_name', models.BooleanField(default=True)),
                ('type', models.IntegerField(choices=[(1, 'Initial Prompt'), (2, 'Narration'), (3, 'Ai'), (4, 'Human')])),
                ('log_number', models.IntegerField()),
                ('safety', models.IntegerField(default=0)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.conversation')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.scenario')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.scenario'),
        ),
    ]
