# Generated by Django 3.1.6 on 2021-04-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='summarize_token',
        ),
        migrations.AlterField(
            model_name='scenario',
            name='mission',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
