# Generated by Django 3.1.6 on 2021-02-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logitem',
            name='is_hidden',
        ),
        migrations.AddField(
            model_name='logitem',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
