# Generated by Django 3.1.6 on 2021-02-14 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logitem',
            old_name='Conversation',
            new_name='conversation',
        ),
    ]
