# Generated by Django 3.1.6 on 2021-02-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20210208_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='frequency_penalty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='scenario',
            name='presence_penalty',
            field=models.DecimalField(decimal_places=3, default=0.6, max_digits=4),
        ),
        migrations.AddField(
            model_name='scenario',
            name='response_length',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='scenario',
            name='temperature',
            field=models.DecimalField(decimal_places=3, default=0.9, max_digits=4),
        ),
        migrations.AddField(
            model_name='scenario',
            name='top_p',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
        ),
    ]
