# Generated by Django 3.1.6 on 2021-02-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20210213_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logitem',
            old_name='is_visible',
            new_name='editable',
        ),
        migrations.AddField(
            model_name='logitem',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
