# Generated by Django 3.1.6 on 2021-02-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20210214_0600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionitem',
            name='option',
        ),
        migrations.AddField(
            model_name='conversation',
            name='scenario_options',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scenario',
            name='options',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='OptionItem',
        ),
    ]
