# Generated by Django 3.1.6 on 2021-04-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20210411_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logitem',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='caution',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='information',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='mission',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
