# Generated by Django 3.1.6 on 2021-02-14 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20210214_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='log_items',
        ),
        migrations.AddField(
            model_name='conversation',
            name='log_items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='demo.logitem'),
            preserve_default=False,
        ),
    ]
