# Generated by Django 3.1.6 on 2021-04-11 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20210411_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logitem',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.conversation'),
        ),
    ]
