# Generated by Django 3.1.6 on 2021-02-19 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20210218_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='status',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='scenario',
            name='statuses',
            field=models.CharField(default='[]', max_length=100),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='ai_name',
            field=models.CharField(default='AI', max_length=20),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='human_name',
            field=models.CharField(default='Human', max_length=20),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='info',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='initial_prompt',
            field=models.CharField(default='Initial Prompt', max_length=200),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='options',
            field=models.CharField(default='{}', max_length=200),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='title',
            field=models.CharField(default='Title', max_length=50),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=20)),
                ('action_id', models.IntegerField()),
                ('type', models.IntegerField(choices=[(1, 'End Conversation'), (2, 'Insert Log Item'), (3, 'Insert User Log Item'), (4, 'Regenerate Response')])),
                ('log_item_params', models.CharField(max_length=100)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.scenario')),
            ],
        ),
    ]
