# Generated by Django 3.1.6 on 2021-02-13 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20210210_0830'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OptioinItem',
            new_name='OptionItem',
        ),
    ]
