# Generated by Django 3.1.6 on 2021-04-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20210411_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logitem',
            name='text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='caution',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='information',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='mission',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
