# Generated by Django 3.1.6 on 2021-02-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20210219_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='condition',
            field=models.IntegerField(choices=[(1, 'None'), (2, 'Conversation State'), (3, 'Time'), (4, 'Token')], default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='trigger',
            field=models.IntegerField(choices=[(1, 'Conversation State'), (2, 'User Input'), (3, 'Time'), (4, 'Token')], default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scenario',
            name='buttons',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scenario',
            name='voice',
            field=models.CharField(choices=[('en-GB_JamesV3Voice', 'Jamesv3'), ('en-US_AllisonV2Voice', 'Allisonv2'), ('en-US_HenryV3Voice', 'Henryv3'), ('en-US_EmilyV3Voice', 'Emilyv3'), ('en-US_AllisonV3Voice', 'Allisonv3'), ('en-US_LisaV3Voice', 'Lisav3'), ('en-US_MichaelV3Voice', 'Michaelv3'), ('en-GB_KateV3Voice', 'Katev3'), ('en-GB_CharlotteV3Voice', 'Charlottev3'), ('en-US_KevinV3Voice', 'Kevinv3'), ('en-US_MichaelV2Voice', 'Michaelv2'), ('en-US_LisaV2Voice', 'Lisav2'), ('en-US_OliviaV3Voice', 'Oliviav3'), ('en-US_MichaelVoice', 'Michael'), ('en-GB_KateVoice', 'Kate'), ('en-US_LisaVoice', 'Lisa'), ('en-US_AllisonVoice', 'Allison'), ('en-AU_CraigVoice', 'Craig'), ('en-AU_MadisonVoice', 'Madison')], default='en-GB_JamesV3Voice', max_length=50),
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.IntegerField(choices=[(1, 'End Conversation'), (2, 'Insert Log Item'), (3, 'Insert User Log Item')]),
        ),
    ]
