# Generated by Django 3.1.6 on 2021-02-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20210214_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='logitem',
            name='log_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
