# Generated by Django 3.1.6 on 2021-08-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_auto_20210415_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='description',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='mission',
        ),
        migrations.AddField(
            model_name='scenario',
            name='category',
            field=models.CharField(default='Roll Play', max_length=100),
        ),
    ]
