# Generated by Django 3.1.6 on 2021-08-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_remove_scenario_caution'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='temp_for_conv_controller',
            field=models.TextField(blank=True, null=True),
        ),
    ]
