# Generated by Django 3.1.6 on 2021-08-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0012_auto_20210827_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='information_en',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='scenario',
            name='title_en',
            field=models.CharField(default='English_title', max_length=50),
        ),
    ]
