# Generated by Django 3.1.6 on 2021-09-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0013_auto_20210827_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='frequency_penalty',
            field=models.DecimalField(decimal_places=3, default=0.5, max_digits=4),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='presence_penalty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='temperature',
            field=models.DecimalField(decimal_places=3, default=0.4, max_digits=4),
        ),
    ]
