# Generated by Django 3.1.6 on 2021-09-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0015_auto_20210904_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='information_cs',
            field=models.CharField(default='Traditional Chinese info', max_length=1000),
        ),
        migrations.AddField(
            model_name='scenario',
            name='information_ct',
            field=models.CharField(default='Simplified Chinese info', max_length=1000),
        ),
        migrations.AddField(
            model_name='scenario',
            name='information_es',
            field=models.CharField(default='Spanish info', max_length=1000),
        ),
        migrations.AddField(
            model_name='scenario',
            name='information_ko',
            field=models.CharField(default='Korean info', max_length=1000),
        ),
        migrations.AddField(
            model_name='scenario',
            name='information_ru',
            field=models.CharField(default='Russian info', max_length=1000),
        ),
        migrations.AddField(
            model_name='scenario',
            name='information_vi',
            field=models.CharField(default='Vietnamese info', max_length=1000),
        ),
        migrations.AddField(
            model_name='scenario',
            name='title_cs',
            field=models.CharField(default='Simplified Chinese title', max_length=50),
        ),
        migrations.AddField(
            model_name='scenario',
            name='title_ct',
            field=models.CharField(default='Traditional Chinese title', max_length=50),
        ),
        migrations.AddField(
            model_name='scenario',
            name='title_es',
            field=models.CharField(default='Spanish Title', max_length=50),
        ),
        migrations.AddField(
            model_name='scenario',
            name='title_ko',
            field=models.CharField(default='Korean Title', max_length=50),
        ),
        migrations.AddField(
            model_name='scenario',
            name='title_ru',
            field=models.CharField(default='Russian Title', max_length=50),
        ),
        migrations.AddField(
            model_name='scenario',
            name='title_vi',
            field=models.CharField(default='Vietnamese Title', max_length=50),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='information',
            field=models.CharField(default='Japanese info', max_length=1000),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='information_en',
            field=models.CharField(default='English info', max_length=1000),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='title_en',
            field=models.CharField(default='English title', max_length=50),
        ),
    ]
