# Generated by Django 3.1.6 on 2021-09-19 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0017_auto_20210919_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='controller_variables',
        ),
    ]
