# Generated by Django 3.1.6 on 2021-09-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0022_auto_20210924_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='expressions',
            new_name='phrases',
        ),
        migrations.AddField(
            model_name='scenario',
            name='message_limit',
            field=models.IntegerField(default='10'),
        ),
    ]
