# Generated by Django 3.1.6 on 2021-09-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0023_auto_20210925_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logitem',
            options={'ordering': ['log_number']},
        ),
        migrations.AddField(
            model_name='scenario',
            name='first_example_response',
            field=models.CharField(default='Unavailable', max_length=100),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='frequency_penalty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='presence_penalty',
            field=models.DecimalField(decimal_places=3, default=0.6, max_digits=4),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='temperature',
            field=models.DecimalField(decimal_places=3, default=0.5, max_digits=4),
        ),
    ]
