# Generated by Django 3.1.6 on 2021-10-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0024_auto_20210925_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='frequency_penalty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='presence_penalty',
            field=models.FloatField(default=0.6),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='temperature',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='top_p',
            field=models.FloatField(default=1),
        ),
    ]
