# Generated by Django 3.1.6 on 2021-10-05 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0026_auto_20211005_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='response_length',
            new_name='max_tokens',
        ),
    ]
