# Generated by Django 3.1.6 on 2021-10-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0027_auto_20211005_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=50)),
                ('example_response', models.CharField(max_length=1000)),
                ('number_of_ai_response', models.IntegerField(default=2)),
                ('allow_user_comment', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='scenario',
            name='last_message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
