# Generated by Django 3.1.6 on 2021-10-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0028_auto_20211006_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='context_for_correction',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='example_response',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='logitem',
            name='corrected_text',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
