# Generated by Django 3.1.6 on 2021-10-08 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0029_auto_20211008_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logitem',
            old_name='scenario',
            new_name='scenario_first',
        ),
        migrations.AlterField(
            model_name='logitem',
            name='scenario_first',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, blank=True, null=True, related_name = "first_logitems", to='demo.scenario'),
        ),
        migrations.AddField(
            model_name='logitem',
            name='scenario_last',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_logitems', to='demo.scenario'),
        ),
    ]
