# Generated by Django 3.1.6 on 2021-10-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0030_auto_20211008_0936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logitem',
            options={'get_latest_by': 'log_number', 'ordering': ['log_number']},
        ),
        migrations.AlterField(
            model_name='scenario',
            name='message_limit',
            field=models.IntegerField(blank=True, default='10', null=True),
        ),
    ]
