# Generated by Django 3.1.6 on 2021-10-15 12:26

import demo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0032_auto_20211009_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, validators=[demo.models.Coupon.validate_digit_length])),
            ],
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='last_message',
        ),
    ]
