# Generated by Django 3.1.6 on 2021-10-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0033_auto_20211015_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='recipient',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
