# Generated by Django 3.1.6 on 2021-10-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0034_auto_20211015_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='amount',
            field=models.IntegerField(default=100),
        ),
    ]
