name: Django

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Setup packages
        run: python3 -m pip install --upgrade -r requirments.txta
      - name: Load Data/Fixtures
        run: |
          python3 manage.py loaddata
      - name: Migrate
        run: |
          python3 manage.py migrate
