name: Fixtures

on:
  pull_request:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  greeting:
    
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Go Env
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1
          stable: true
      - name: Make JSON from CSV
        run: go run ci/csv_to_json.go -o=./demo/fixtures/scenarios.json
      - name: Commit
        run: sh ci/auto_commit.sh "Make JSON fixtures from Google Sheet."
