name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ production ]
  workflow_dispatch: [ production ]

jobs:
  heroku-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          echo I should push to Heroku now.
