name: Deploy

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.10.9 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API}}
          heroku_app_name: "convbackend"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
