name: Make JSON

on:
  push:
    branches:
    - "*"
  schedule:
    - cron: '* * * * *'

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps: 
      - name: Setup Go Env
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1
          stable: true
      - name: Run Make JSON
        run: go run gsheet_to_json.go -o=./demo/fixtures/scenarios.json
      - name: Commit
        uses: docker://cdssnc/auto-commit-github-action
